version: '3'

services:
  traefik:
    image: traefik:v2.2
    command: --providers.docker
    ports:
      - "80:80"
      - "8086:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  whoami:
    image: containous/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost.com`)"
      # This example uses "Selective Authentication"
      - "traefik.http.routers.whoami.middlewares=traefik-forward-auth"

  traefik-forward-auth:
    # image: thomseddon/traefik-forward-auth:2
    image: traefik-forward-auth:latest
    environment:
      - DEFAULT_PROVIDER=wso2
      - PROVIDERS_WSO2_CLIENT_ID=<secret> # set in env_file
      - PROVIDERS_WSO2_CLIENT_SECRET=<secret>  # set in env_file
      - PROVIDERS_WSO2_GRANT_TYPE=client_credentials # grant_type=client_credentials
      - PROVIDERS_WSO2_TOKEN_HOST=gw.api.cloud.sphereon.com
      - SECRET=something-random
      # INSECURE_COOKIE is required if not using a https entrypoint
      - INSECURE_COOKIE=true
      - LOG_LEVEL=debug
    labels:
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://traefik-forward-auth:4181"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=Authorization"
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"
